
languageCode = "en"
defaultContentLanguage = "en"

# 网站标题
title = "testBlog"                        

theme = "zozo"

# 自动检测是否包含 中文\日文\韩文
hasCJKLanguage = true                   

summaryLength = 100

# 首页显示文章数量
paginate = 4        

enableEmoji = true

# Google统计代码
googleAnalytics = "" 

# Disqus评论系统代码              
disqusShortname = ""                   

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

# 必需
[author]                               
  name = "YCQ"

[blackfriday]
  smartypants = false

# 配置菜单
[[menu.main]]                          
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  # 网站二级标题
  subTitle = "副标题"


  # 网站页脚标语                                       
  footerSlogan = "学习记录" 


  # 网站关键字                                 
  keywords = []  


  # 网站描述                                   
  description = ""


  # 是否使用mathjax（数学公式）                     
  enableMathJax = true


  # 是否显示文章摘要                                                
  enableSummary = true
                                                   
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
# 社交地址配置
[social]
  github = " "
  twitter = " "
  facebook = " "
  weibo = " "
  instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
